# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from servicingmerchantcasemanagementapi.api_helper import APIHelper


class AdditionalCaseDetails(object):

    """Implementation of the 'AdditionalCaseDetails' model.

    TODO: type model description here.

    Attributes:
        case_number (str): Unique number assigned to the case (Auto generated
            once case is created)
        category (str): Case category. High level grouping of case types.
        case_type (str): Case type for selected category for the case
        priority (Priority1Enum): Defines time limit for case resolution
        status (Status2Enum): Status of a case
        sub_status (SubStatusEnum): Only applicable when status is Pending
        reason (str): The reason a case was created
        subject (str): Brief description of the customer’s question or
            feedback.
        description (str): User defined field.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "case_number": 'caseNumber',
        "category": 'category',
        "case_type": 'caseType',
        "priority": 'priority',
        "status": 'status',
        "sub_status": 'subStatus',
        "reason": 'reason',
        "subject": 'subject',
        "description": 'description'
    }

    _optionals = [
        'case_number',
        'category',
        'case_type',
        'priority',
        'status',
        'sub_status',
        'reason',
        'subject',
        'description',
    ]

    def __init__(self,
                 case_number=APIHelper.SKIP,
                 category=APIHelper.SKIP,
                 case_type=APIHelper.SKIP,
                 priority=APIHelper.SKIP,
                 status=APIHelper.SKIP,
                 sub_status=APIHelper.SKIP,
                 reason=APIHelper.SKIP,
                 subject=APIHelper.SKIP,
                 description=APIHelper.SKIP):
        """Constructor for the AdditionalCaseDetails class"""

        # Initialize members of the class
        if case_number is not APIHelper.SKIP:
            self.case_number = case_number 
        if category is not APIHelper.SKIP:
            self.category = category 
        if case_type is not APIHelper.SKIP:
            self.case_type = case_type 
        if priority is not APIHelper.SKIP:
            self.priority = priority 
        if status is not APIHelper.SKIP:
            self.status = status 
        if sub_status is not APIHelper.SKIP:
            self.sub_status = sub_status 
        if reason is not APIHelper.SKIP:
            self.reason = reason 
        if subject is not APIHelper.SKIP:
            self.subject = subject 
        if description is not APIHelper.SKIP:
            self.description = description 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        case_number = dictionary.get("caseNumber") if dictionary.get("caseNumber") else APIHelper.SKIP
        category = dictionary.get("category") if dictionary.get("category") else APIHelper.SKIP
        case_type = dictionary.get("caseType") if dictionary.get("caseType") else APIHelper.SKIP
        priority = dictionary.get("priority") if dictionary.get("priority") else APIHelper.SKIP
        status = dictionary.get("status") if dictionary.get("status") else APIHelper.SKIP
        sub_status = dictionary.get("subStatus") if dictionary.get("subStatus") else APIHelper.SKIP
        reason = dictionary.get("reason") if dictionary.get("reason") else APIHelper.SKIP
        subject = dictionary.get("subject") if dictionary.get("subject") else APIHelper.SKIP
        description = dictionary.get("description") if dictionary.get("description") else APIHelper.SKIP
        # Return an object of this model
        return cls(case_number,
                   category,
                   case_type,
                   priority,
                   status,
                   sub_status,
                   reason,
                   subject,
                   description)
