# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Attachment(object):

    """Implementation of the 'Attachment' model.

    TODO: type model description here.

    Attributes:
        file_name (str): Name of the file with extension
        file_content (binary): Content of the file. Accepts upto 4 MB

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "file_name": 'fileName',
        "file_content": 'fileContent'
    }

    def __init__(self,
                 file_name=None,
                 file_content=None):
        """Constructor for the Attachment class"""

        # Initialize members of the class
        self.file_name = file_name 
        self.file_content = file_content 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        file_name = dictionary.get("fileName") if dictionary.get("fileName") else None
        file_content = dictionary.get("fileContent") if dictionary.get("fileContent") else None
        # Return an object of this model
        return cls(file_name,
                   file_content)
