# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from servicingmerchantcasemanagementapi.api_helper import APIHelper


class CallerInfo(object):

    """Implementation of the 'CallerInfo' model.

    TODO: type model description here.

    Attributes:
        requestor (str): Name of the requestor
        email (str): Requestor's email address
        phone_number (str): Requestor's phone number

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "requestor": 'requestor',
        "email": 'email',
        "phone_number": 'phoneNumber'
    }

    _optionals = [
        'phone_number',
    ]

    def __init__(self,
                 requestor=None,
                 email=None,
                 phone_number=APIHelper.SKIP):
        """Constructor for the CallerInfo class"""

        # Initialize members of the class
        self.requestor = requestor 
        self.email = email 
        if phone_number is not APIHelper.SKIP:
            self.phone_number = phone_number 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        requestor = dictionary.get("requestor") if dictionary.get("requestor") else None
        email = dictionary.get("email") if dictionary.get("email") else None
        phone_number = dictionary.get("phoneNumber") if dictionary.get("phoneNumber") else APIHelper.SKIP
        # Return an object of this model
        return cls(requestor,
                   email,
                   phone_number)
