# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from servicingmerchantcasemanagementapi.api_helper import APIHelper


class CaseNumberAttachmentsBody(object):

    """Implementation of the 'caseNumber_attachments_body' model.

    TODO: type model description here.

    Attributes:
        file (binary): Attachment file

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "file": 'file'
    }

    _optionals = [
        'file',
    ]

    def __init__(self,
                 file=APIHelper.SKIP):
        """Constructor for the CaseNumberAttachmentsBody class"""

        # Initialize members of the class
        if file is not APIHelper.SKIP:
            self.file = file 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        file = dictionary.get("file") if dictionary.get("file") else APIHelper.SKIP
        # Return an object of this model
        return cls(file)
