# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CountryEnum(object):

    """Implementation of the 'country' enum.

    TODO: type enum description here.

    Attributes:
        US: TODO: type description here.
        GB: TODO: type description here.

    """
    US = 'US'

    GB = 'GB'

