# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CreateCommentRequest(object):

    """Implementation of the 'CreateCommentRequest' model.

    TODO: type model description here.

    Attributes:
        comment (str): Comment to be added on the case

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "comment": 'comment'
    }

    def __init__(self,
                 comment=None):
        """Constructor for the CreateCommentRequest class"""

        # Initialize members of the class
        self.comment = comment 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        comment = dictionary.get("comment") if dictionary.get("comment") else None
        # Return an object of this model
        return cls(comment)
