# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from servicingmerchantcasemanagementapi.api_helper import APIHelper


class CreateCaseResponse(object):

    """Implementation of the 'CreateCaseResponse' model.

    TODO: type model description here.

    Attributes:
        case_number (str): Unique number assigned to the case (Auto generated
            once case is created)

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "case_number": 'caseNumber'
    }

    _optionals = [
        'case_number',
    ]

    def __init__(self,
                 case_number=APIHelper.SKIP):
        """Constructor for the CreateCaseResponse class"""

        # Initialize members of the class
        if case_number is not APIHelper.SKIP:
            self.case_number = case_number 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        case_number = dictionary.get("caseNumber") if dictionary.get("caseNumber") else APIHelper.SKIP
        # Return an object of this model
        return cls(case_number)
