# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from servicingmerchantcasemanagementapi.models.attachment import Attachment


class CreateAttachmentRequest(object):

    """Implementation of the 'CreateAttachmentRequest' model.

    TODO: type model description here.

    Attributes:
        attachments (List[Attachment]): Attachment file names

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "attachments": 'attachments'
    }

    def __init__(self,
                 attachments=None):
        """Constructor for the CreateAttachmentRequest class"""

        # Initialize members of the class
        self.attachments = attachments 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        attachments = None
        if dictionary.get('attachments') is not None:
            attachments = [Attachment.from_dictionary(x) for x in dictionary.get('attachments')]
        # Return an object of this model
        return cls(attachments)
