# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DateTypeEnum(object):

    """Implementation of the 'DateType' enum.

    Type of date

    Attributes:
        OPENDATE: TODO: type description here.
        CLOSEDATE: TODO: type description here.

    """
    OPENDATE = 'openDate'

    CLOSEDATE = 'closeDate'

