# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class EntityTypeEnum(object):

    """Implementation of the 'EntityType' enum.

    Type of the entity, Required for US entities

    Attributes:
        MERCHANT: TODO: type description here.
        CHAIN: TODO: type description here.
        PARTNER: TODO: type description here.

    """
    MERCHANT = 'MERCHANT'

    CHAIN = 'CHAIN'

    PARTNER = 'PARTNER'

