# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrderByEnum(object):

    """Implementation of the 'OrderBy' enum.

    Order search results in ascnding or descending order.

    Attributes:
        ASC: TODO: type description here.
        DESC: TODO: type description here.

    """
    ASC = 'ASC'

    DESC = 'DESC'

