# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from servicingmerchantcasemanagementapi.api_helper import APIHelper


class PaginationType(object):

    """Implementation of the 'PaginationType' model.

    Use for pagination.

    Attributes:
        limit (str): The maximum number of entries to return. If the value
            exceeds the maximum, then the maximum value will be used.
        offset (str): The offset used for page results

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "limit": 'limit',
        "offset": 'offset'
    }

    _optionals = [
        'limit',
        'offset',
    ]

    def __init__(self,
                 limit='25',
                 offset='1'):
        """Constructor for the PaginationType class"""

        # Initialize members of the class
        self.limit = limit 
        self.offset = offset 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        limit = dictionary.get("limit") if dictionary.get("limit") else '25'
        offset = dictionary.get("offset") if dictionary.get("offset") else '1'
        # Return an object of this model
        return cls(limit,
                   offset)
