# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PriorityEnum(object):

    """Implementation of the 'Priority' enum.

    Defines time limit for case resolution

    Attributes:
        URGENT: TODO: type description here.
        HIGH: TODO: type description here.
        MEDIUM: TODO: type description here.
        LOW: TODO: type description here.
        ENUM_CRITICAL  4HOURS: TODO: type description here.
        ENUM_HIGH  24 HRS: TODO: type description here.
        ENUM_MEDIUM 48 HOURS: TODO: type description here.
        ENUM_LOW 4DAYS: TODO: type description here.
        ENUM_STANDARD REQUEST: TODO: type description here.
        ENUM_RUSH REQUEST: TODO: type description here.
        OVERNIGHT: TODO: type description here.
        ENUM_THREE DAY: TODO: type description here.
        ENUM_TWO DAY: TODO: type description here.
        GROUND: TODO: type description here.
        NONE: TODO: type description here.

    """
    URGENT = 'Urgent'

    HIGH = 'High'

    MEDIUM = 'Medium'

    LOW = 'Low'

    ENUM_CRITICAL_4HOURS = 'Critical < 4hours'

    ENUM_HIGH_24_HRS = 'High < 24 hrs'

    ENUM_MEDIUM_48_HOURS = 'Medium <48 hours'

    ENUM_LOW_4DAYS = 'Low <4days'

    ENUM_STANDARD_REQUEST = 'Standard Request'

    ENUM_RUSH_REQUEST = 'Rush Request'

    OVERNIGHT = 'Overnight'

    ENUM_THREE_DAY = 'Three Day'

    ENUM_TWO_DAY = 'Two Day'

    GROUND = 'Ground'

    ENUM_NONE = 'None'

