# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatusEnum(object):

    """Implementation of the 'Status' enum.

    Case status

    Attributes:
        NEW: TODO: type description here.
        ENUM_IN PROGRESS: TODO: type description here.
        PENDING: TODO: type description here.
        CLOSED: TODO: type description here.

    """
    NEW = 'New'

    ENUM_IN_PROGRESS = 'In Progress'

    PENDING = 'Pending'

    CLOSED = 'Closed'

