# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Status2Enum(object):

    """Implementation of the 'Status2' enum.

    Status of a case

    Attributes:
        NEW: TODO: type description here.
        PENDING: TODO: type description here.
        ENUM_IN PROGRESS: TODO: type description here.
        CLOSED: TODO: type description here.

    """
    NEW = 'New'

    PENDING = 'Pending'

    ENUM_IN_PROGRESS = 'In Progress'

    CLOSED = 'Closed'

