# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SubStatusEnum(object):

    """Implementation of the 'SubStatus' enum.

    Only applicable when status is Pending

    Attributes:
        ENUM_PENDING INTERNAL: TODO: type description here.
        ENUM_PENDING EXTERNAL: TODO: type description here.

    """
    ENUM_PENDING_INTERNAL = 'Pending Internal'

    ENUM_PENDING_EXTERNAL = 'Pending External'

