# -*- coding: utf-8 -*-

"""
servicingmerchantcasemanagementapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from servicingmerchantcasemanagementapi.api_helper import APIHelper


class LookupControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(LookupControllerTests, cls).setUpClass()
        cls.controller = cls.client.lookup
        cls.response_catcher = cls.controller.http_call_back

    # Get list of all active case categories from WolrdPay.
    def test_get_case_categories(self):
        # Parameters for the API call
        v_correlation_id = '24578e35-9bd2-238f-b4c2-0bc9ad9aed2b'
        country = 'US'

        # Perform the API call through the SDK function
        result = self.controller.get_case_categories(v_correlation_id, country)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"categories":["Account Management","Collections","Configuration/D'
            'ownloads","Contract Management","Disputes"]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Retrieve list of case types for specific case category with WolrdPay
    def test_get_case_category_types(self):
        # Parameters for the API call
        v_correlation_id = '24578e35-9bd2-238f-b4c2-0bc9ad9aed2b'
        category = 'Account Management'

        # Perform the API call through the SDK function
        result = self.controller.get_case_category_types(v_correlation_id, category)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"category":"Account Management","caseTypes":["Add Location","Auth'
            'orized User Maintenance","Close Account","Dealer/Partner/RM Change'
            '"]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Retrieve list of all case reasons from WolrdPay.
    def test_get_case_reasons(self):
        # Parameters for the API call
        v_correlation_id = '24578e35-9bd2-238f-b4c2-0bc9ad9aed2b'

        # Perform the API call through the SDK function
        result = self.controller.get_case_reasons(v_correlation_id)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"reasons":["Escalation","Repeat Call","Service Activity","Status '
            'Update"]}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

